/*


Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

#include <stdio.h>
#include "defines.h"

#define SEQENCE_LIMIT 4000000
int main()
{
	int sum =2;
	int f0 = 1;
	int f1 = 2;
	int f2 = 0;
	while(f2 < SEQENCE_LIMIT){
		f2 = f0 +f1;
		if(!(f2 & BIT(0))){
			sum +=f2;
		}
		f0 = f1;
		f1 = f2;
	}

	ANSWER_INT(sum);
}
